#!/bin/bash

docker exec -i mysql-db mysql -uroot -psecurerootpassword < structure.sql
docker exec -i mysql-db mysql -uroot -psecurerootpassword < data.sql
docker exec -i mysql-db mysql -uroot -psecurerootpassword < data_kilit.sql
